apiVersion: v1
data:
  mapRoles: |
        - rolearn: arn:aws:iam::292622099037:role/eksctl-brain-eks-cluster-nodegroup-NodeInstanceRole-dIXcIAwRtdYS
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::292622099037:role/service-role/codebuild-brain-tasks-role
      username: codebuild
      groups:
        - system:masters
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::292622099037:role/eksctl-brain-eks-cluster-nodegroup-NodeInstanceRole-dIXcIAwRtdYS\n  groups:\n    - system:bootstrappers\n    - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n- rolearn: arn:aws:iam::292622099037:role/service-role/codebuild-brain-tasks-role\n  username: codebuild\n  groups:\n    - system:masters\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-02-17T15:18:31Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"18043","uid":"8d87b977-29e2-4b5b-9a78-361de562eea3"}}
  creationTimestamp: "2026-02-17T15:18:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "21844"
  uid: 8d87b977-29e2-4b5b-9a78-361de562eea3
