apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::292622099037:role/eksctl-brain-eks-cluster-nodegroup-NodeInstanceRole-dIXcIAwRtdYS
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

    - rolearn: arn:aws:iam::292622099037:role/service-role/codebuild-brain-tasks-role
      username: codebuild
      groups:
        - system:masters

kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
  resourceVersion: "18043"
  uid: 8d87b977-29e2-4b5b-9a78-361de562eea3
