apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::292622099037:role/eksctl-brain-eks-cluster-nodegroup-NodeInstanceRole-dIXcIAwRtdYS
      groups:
        - system:bootstrappers
        - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::292622099037:role/service-role/codebuild-brain-tasks-role
      username: codebuild
      groups:
        - system:masters
